name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create zip archive
        run: |
          mkdir release_content
          cp -r "[Original]" release_content/
          cp -r "[Custom]" release_content/
          zip -r release.zip release_content

      - name: Delete existing release
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest Release
          body: |
            # Install  
            Unzip this folder directly into your TazUO folder. Yes to override files.
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
